### ISSUE TITLE
Tilde should be relative to package

### ISSUE THREAD

**Issue by Tvrqvoise** [webpack/less-loader#122]
Let's say I have a project called `child`.  In child, I load a url like this:
```less
// filename: child.less
background-image: url('~/images/guy-fieri.jpeg');
```

Let's say I also have another project called `parent`, which lists `child` as a dependency.  Inside a less file in `parent` I load `child`'s styles like:
```less
// filename: parent.less
import "~child/child.less"
```

Webpack sees the url import and tries to look it up as:
```
parent/images/guy-fieri.jpeg
````

Instead of how I would expect:
```
parent/node_modules/child/images/guy-fieri.jpeg
```

Of course, I could change the import inside `child` to be `url('~child/images/guy-fieri')`, but then child cannot resolve that file itself -- it can only be resolved from outside.  This makes it very difficult to have one project depend upon the styles of another.

If I'm wrong that this behavior is expected, any other solutions to my issue are welcomed.

**Comment by jhnns** [comment]
> Webpack sees the url import and tries to look it up as:

No, that's not correct. Webpack treats paths starting with a `~[a-z]` as module directory, which means that it is resolved like `node_modules` in node. However, if you import something from `~/[a-z]`, webpack will look into your home folder (on Linux/macOS).

Inside the child project, there is no need to import something from `~` since you should always use relative paths as long as you're inside the same project.

I guess, there's something wrong with your webpack resolve configuration. If you want to track down the problem, copy the files into an example project and start with a fresh webpack configuration. Don't add resolve options until you fully understand the impact.
