### ISSUE TITLE
Create source maps

### ISSUE THREAD

**Issue by wolever** [webpack/less-loader#16]
It would be very helpful if there was some way to emit source maps for .less files.

**Comment by feroc1ty** [comment]
:+1: 

[less.render](https://github.com/webpack/less-loader/blob/master/index.js#L46) already output source maps but I am not sure how to combine them with css-loader.

because I am not webpack expert I have dig into [coffee-loader](https://github.com/webpack/coffee-loader/blob/master/index.js#L39) to figure out how he is passing source maps so I have tried to add
```javascript
var map = JSON.parse(result.map);
map.sourceContent = [input];
cb(null, result.css, map);
```
[to](https://github.com/webpack/less-loader/blob/master/index.js#L53) but no luck :unamused: 
so it would be great if someone who know how to combine these things could help to figure this one out

also it would be useful if these will work with autoprefixer

**Comment by 3sv** [comment]
I'm using webpack with LESS loader and autoprefixer and got working sourcemaps with the following loader config line:
```javascript
test: /\.less$/,
loader: 'style-loader/useable!css-loader?sourceMap!autoprefixer-loader?browsers=last 2 version!less-loader?sourceMap=source-map-less-inline'
```

To get this working you need to make a change to style-loader and to less-loader. I didn't find the time yet to create a proper merge request.

in style loader: 'stylesheet/css' should be changed to 'text/css':
```javascript
---node_modules/style-loader/addStyles.js
+++ node_modules/style-loader/addStyles.js
@@ -171,7 +171,7 @@
	if(sourceMap && typeof btoa === "function") {
		try {
			css += "\n/*# sourceMappingURL=data:application/json;base64," + btoa(JSON.stringify(sourceMap)) + " */";
-			css = "@import url(\"data:stylesheet/css;base64," + btoa(css) + "\")";
+			css = "@import url(\"data:text/css;base64," + btoa(css) + "\")";
		} catch(e) {}
	}
```


In less-loader the option to create sourcemaps should be passed to a sub-object with the key 'sourceMap'. The query paramaters are passed to the top level config. The code should be changed so that all sourcemap specific options are passed in the sourceMap object instead of the parent config.
To just get inline sourcemaps:
```javascript
--- node_modules/less-loader/index.js
+++ node_modules/less-loader/index.js
@@ -21,7 +21,10 @@
 		filename: this.resource,
 		paths: [],
 		relativeUrls: true,
-		compress: !!this.minimize
+       compress: !!this.minimize,
+        sourceMap: {
+            sourceMapFileInline : true
+        }
 	};
 	var webpackPlugin = {
 		install: function(less, pluginManager) {
```


Note that these changes are only tested with the '/usable' feature from the style-loader. This is the mode where you can manually call .use() and .unuse() on the required less files. 

Feel free to make these changes general and make proper merge requests for them.

Once you get this the sourcemaps are working but the file names are really long. To workaround this I used this change in style loader to split the path:
node_modules/style-loader/addStyles.js
```javascript
var basedirectoryName = 'repoName';
    sourceMap.file = sourceMap.file.split(basedirectoryName).pop();
    for(var i = 0; i < sourceMap.sources.length; i++) {
        sourceMap.sources[i] = sourceMap.sources[i].split(basedirectoryName).pop();
    }

	if(sourceMap && typeof btoa === "function") {
		try {
			css += "\n/*# sourceMappingURL=data:application/json;base64," + btoa(JSON.stringify(sourceMap)) + " */";
			css = "@import url(\"data:text/css;base64," + btoa(css) + "\")";
		} catch(e) {}
	}
```
This is not good enough to be a pull request as it needs the basedirectoryName. But in that place something can be changed to get shorter/usable filenames.


Also note that once source-maps are enabled on the css loader you can no longer use import statements in you're css files. This is not supported in external stylesheets, and this seems the only mode that supports sourcemaps. This is only a problem for the import's that get not resolved before the browser context, so the imports that are replaced by less-loader or url-loader are working fine.

**Comment by 3sv** [comment]
You can ignore my previous post and see an example at
https://github.com/3sv/webpack-less-autoprefixer-sourcemaps-demo

webpack + less + autoprefixer with source maps

**Comment by feroc1ty** [comment]
thanks @3sv for help I was using old version of less :)
