### ISSUE TITLE
[question] moving from lessbuildify

### ISSUE THREAD

**Issue by AsaAyers** [webpack/less-loader#49]
I have a project that is using browserify and [lessbuildify](https://www.npmjs.com/package/lessbuildify) and I'm looking at moving to webpack/less-loader.

With lessbuildify when I `require('path/to/main.less')`, `require('./foo.less')`, `require('./bar.less')` instead of compiling individually, it builds a list and compiles a file it generates that simply contains a set of `@include`s. It would look something like this:

```less
/* all the paths get expanded */
@include "path/to/main.less";
@include "full/path/to/foo.less";
@include "full/path/to/bar.less"
```

Is this possible or advisable with `less-loader`? The blocker in adopting `less-loader` is that `foo.less` and `bar.less` depend on variables defined in `main.less` but they have never needed to `@include` it explicitly. I think this might be bad practice, but I'm looking for a way forward that doesn't involve major changes to all of my less files.

note: my example is simplified and the actual `main.less` is actually a collection of files rather than one central file I should `@include`.

**Comment by jhnns** [comment]
Thanks for your comment. Didn't know how lessbuildify is handling it at browserify.

Unfortunately I don't think that this is possible because of two reasons:

1. Webpack's loader are stateless by default. This means that we can't collect multiple files and then just run `less.render()` before the bundle is emitted. Lessbuildify, on the other hand, is stateful and [is storing all files in a variable inside the function's scope](https://github.com/deepsweet/lessbuildify/blob/634f65a8f33590093e3e8fd30700d5fb44acaf48/index.js#L31) but that seems wrong to me, because then multiple builds are not independent anymore. I'd even assume that this is bad practice for browserify transforms (though I'm not sure).

2. The less-loader does not know how the user will consume the result. Usually you'd pass it on to the css-loader and then to the style-loader which adds the string as stylesheet to the document. But what if the user wanted to use the css result for different purposes? We don't know...

Achieving truly modular styles and avoiding multiple builds is still a puzzle imho. The current best practice is still one `main.less` which imports all the other styles. In order to avoid code duplication you can also use [@import (reference)](http://lesscss.org/features/#import-options-reference). We've already talked about this at #7.

However, I think this could be achieved with a Webpack plugin which knows about the build state of the current bundle. Actually, a Webpack plugin is closer to a browserify transform than a loader because it can hook into specific events when the bundle is generated.

**Comment by AsaAyers** [comment]
Thanks for the response. I didn't know about `@import (reference)` or that loaders are stateless.

In the end I just went through my whole codebase and converted `require('whatever.less')` into `@import "whatever.less";` from a central file.
